version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./api:/app/api
      - ./recommender:/app/recommender  # Montamos la carpeta recommender  
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/investdb

  recommender:
    build: ./recommender
    depends_on:
      - db
    volumes:
      - ./recommender:/app/recommender  # Asegúrate de que también se comparta el volumen si es necesario  
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/investdb

  etl:
    build: ./etl
    depends_on:
      - db
    env_file:
      - .env
    command: ["python", "run_etl.py"]

  worker:
    build: ./worker
    depends_on:
      - redis
      - db
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis:7
    restart: always

volumes:
  pgdata:
